const questions = [
  { question: "At what temperature are Celsius and Fahrenheit equal?", options: ["A. -40°", "B. 0°", "C. 32°", "D. 100°"], correct: "A" },
  { question: "Roughly how long does sunlight take to reach Earth?", options: ["A. 4 min", "B. 8 min", "C. 12 min", "D. 24 min"], correct: "B" },
  { question: "What are the four states of matter?", options: ["A. Solid, liquid, gas, plasma", "B. Solid, liquid, gas, vapor", "C. Plasma, vapor, liquid, crystal", "D. Solid, liquid, vapor, dust"], correct: "A" },
  { question: "Which metal is liquid at room temperature?", options: ["A. Gallium", "B. Bromine", "C. Mercury", "D. Cesium"], correct: "C" },
  { question: "A Geiger counter measures what?", options: ["A. Light", "B. Radiation", "C. Pressure", "D. Humidity"], correct: "B" },
  { question: "What is the largest desert on Earth?", options: ["A. Sahara", "B. Gobi", "C. Antarctica", "D. Arabian"], correct: "C" },
  { question: "Who was the first human in space?", options: ["A. Neil Armstrong", "B. Buzz Aldrin", "C. Yuri Gagarin", "D. Alan Shepard"], correct: "C" },
  { question: "Bronze is an alloy of which two elements?", options: ["A. Copper & Zinc", "B. Copper & Tin", "C. Iron & Carbon", "D. Silver & Tin"], correct: "B" },
  { question: "What is the tallest type of grass?", options: ["A. Wheat", "B. Bamboo", "C. Sugarcane", "D. Corn"], correct: "B" },
  { question: "How many bones do sharks have?", options: ["A. 0", "B. 206", "C. 108", "D. 56"], correct: "A" },
  { question: "Electric current is measured in which units?", options: ["A. Volts", "B. Coulombs", "C. Amperes", "D. Watts"], correct: "C" },
  { question: "A magnifying glass uses what kind of lens?", options: ["A. Concave", "B. Convex", "C. Cylindrical", "D. Fresnel"], correct: "B" },
  { question: "Electric resistance is measured in what unit?", options: ["A. Ohms", "B. Teslas", "C. Joules", "D. Henrys"], correct: "A" },
  { question: "Most recognized model of the universe’s origin?", options: ["A. Steady State", "B. Big Bang", "C. String Theory", "D. Plasma Theory"], correct: "B" },
  { question: "Earth's primary source of energy is?", options: ["A. Moon", "B. Core", "C. Sun", "D. Oceans"], correct: "C" },
  { question: "What two elements make up water?", options: ["A. Hydrogen & Oxygen", "B. Hydrogen & Nitrogen", "C. Carbon & Oxygen", "D. Sodium & Chlorine"], correct: "A" },
  { question: "What is the deepest point in the ocean?", options: ["A. Java Trench", "B. Mariana Trench", "C. Tonga Trench", "D. Puerto Rico Trench"], correct: "B" },
  { question: "CPU stands for?", options: ["A. Computer Power Unit", "B. Central Process Unit", "C. Central Processing Unit", "D. Control Processing Unit"], correct: "C" },
  { question: "Molten rock before eruption is called?", options: ["A. Lava", "B. Magma", "C. Basalt", "D. Pumice"], correct: "B" },
  { question: "Dinosaur time periods?", options: ["A. Paleozoic, Mesozoic, Cenozoic", "B. Triassic, Jurassic, Cretaceous", "C. Cambrian, Ordovician, Silurian", "D. Permian, Triassic, Jurassic"], correct: "B" },
  { question: "One metal that is liquid at room temperature?", options: ["A. Mercury", "B. Gold", "C. Silver", "D. Iron"], correct: "A" },
  { question: "Unit of force in SI?", options: ["A. Joule", "B. Newton", "C. Watt", "D. Pascal"], correct: "B" },
  { question: "\"For every action, there's an equal and opposite reaction\" is which law?", options: ["A. Newton’s First", "B. Second", "C. Third", "D. Law of Gravity"], correct: "C" },
  { question: "Type of energy in a compressed spring?", options: ["A. Kinetic", "B. Thermal", "C. Elastic potential", "D. Chemical potential"], correct: "C" },
  { question: "Unit of power in SI?", options: ["A. Newton", "B. Joule", "C. Watt", "D. Volt"], correct: "C" },
  { question: "Who developed general relativity?", options: ["A. Newton", "B. Einstein", "C. Bohr", "D. Hawking"], correct: "B" },
  { question: "Term for light bending between mediums?", options: ["A. Reflection", "B. Absorption", "C. Refraction", "D. Diffraction"], correct: "C" },
  { question: "Type of wave that needs a medium?", options: ["A. Light wave", "B. Electromagnetic", "C. Mechanical wave", "D. Radio wave"], correct: "C" },
  { question: "SI unit of electric current?", options: ["A. Volt", "B. Ohm", "C. Ampere", "D. Watt"], correct: "C" },
  { question: "Materials that resist electric flow are called?", options: ["A. Conductors", "B. Insulators", "C. Semiconductors", "D. Resistors"], correct: "B" },
  { question: "Temperature increase → wave frequency...?", options: ["A. Increases", "B. Decreases", "C. Stays same", "D. First increases, then decreases"], correct: "B" },
  { question: "Type of lens thicker at edges?", options: ["A. Concave", "B. Convex", "C. Fresnel", "D. Plano"], correct: "A" },
  { question: "Effect where sound frequency shifts due to motion?", options: ["A. Doppler", "B. Diffraction", "C. Interference", "D. Reflection"], correct: "A" },
  { question: "Only liquid metal at room temp besides mercury?", options: ["A. Bromine", "B. Gallium", "C. Sodium", "D. Caesium"], correct: "B" },
  { question: "What unit measures temperature?", options: ["A. Joule", "B. Kelvin", "C. Watt", "D. Ampere"], correct: "B" },
  { question: "What is a mechanical wave?", options: ["A. Doesn’t need medium", "B. Needs medium to travel", "C. Travels in vacuum", "D. Only travels in solids"], correct: "B" },
  { question: "The center of an atom is called?", options: ["A. Nucleus", "B. Electron", "C. Proton", "D. Neutron"], correct: "A" },
  { question: "Which gas do plants absorb?", options: ["A. Oxygen", "B. Carbon dioxide", "C. Nitrogen", "D. Hydrogen"], correct: "B" },
  { question: "Largest mammal?", options: ["A. Elephant", "B. Blue whale", "C. Giraffe", "D. Hippopotamus"], correct: "B" },
  { question: "Process turning liquid to gas?", options: ["A. Evaporation", "B. Condensation", "C. Precipitation", "D. Sublimation"], correct: "A" },
  { question: "What do bees collect from flowers?", options: ["A. Honey", "B. Nectar", "C. Pollen", "D. Wax"], correct: "B" },
  { question: "What do you call a baby frog?", options: ["A. Tadpole", "B. Cub", "C. Larva", "D. Fry"], correct: "A" },
  { question: "Which fruit is linked to gravity legend?", options: ["A. Orange", "B. Cherry", "C. Apple", "D. Pear"], correct: "C" },
  { question: "What is the hardest natural substance?", options: ["A. Iron", "B. Quartz", "C. Diamond", "D. Gold"], correct: "C" },
  { question: "What organ pumps blood?", options: ["A. Brain", "B. Heart", "C. Kidney", "D. Lung"], correct: "B" },
  { question: "How many chromosomes do humans have?", options: ["A. 23", "B. 46", "C. 44", "D. 22"], correct: "B" },
  { question: "What measures atmospheric pressure?", options: ["A. Thermometer", "B. Barometer", "C. Altimeter", "D. Anemometer"], correct: "B" },
  { question: "Which is the powerhouse of the cell?", options: ["A. Nucleus", "B. Golgi body", "C. Mitochondria", "D. Ribosome"], correct: "C" },
  { question: "Largest volcano in the solar system?", options: ["A. Mauna Loa", "B. Olympus Mons", "C. Vesuvius", "D. Mount Etna"], correct: "B" },
  { question: "What is DNA stand for?", options: ["A. Deoxyribonucleic Acid", "B. Deoxynucleic Acid", "C. Dioxyribonucleic Acid", "D. Dinucleic Acid"], correct: "A" },
  { question: "At what temperature does water freeze (°C)?", options: ["A. 32", "B. 100", "C. 0", "D. -40"], correct: "C" },
  { question: "Which planet is closest to the sun?", options: ["A. Venus", "B. Mars", "C. Mercury", "D. Earth"], correct: "C" },
  { question: "What is the unit of force?", options: ["A. Newton", "B. Joule", "C. Watt", "D. Pascal"], correct: "A" },
  { question: "Gravity pulls objects toward?", options: ["A. Moon", "B. Center of Earth", "C. Sun", "D. Space"], correct: "B" },
  { question: "What is the chemical symbol for gold?", options: ["A. Ga", "B. Gd", "C. Au", "D. Ag"], correct: "C" }
];